// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  ServerSentEventsResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  GetConfigData,
  GetConfigErrors,
  GetConfigResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  StreamEventsData,
  StreamEventsErrors,
  StreamEventsResponse,
  StreamEventsResponses,
} from './types.gen';
import { zGetConfigResponse, zGetHealthResponse, zStreamEventsResponse } from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Report daemon health
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    responseValidator: async data => await zGetHealthResponse.parseAsync(data),
    url: '/api/v1/health',
    ...options,
  });

/**
 * Read the public configuration
 *
 * What the UI needs before it can render: the daemon's name and build. The same object is injected into `index.html` as `window.__CONFIG__`, so the first render does not wait for this request; the UI reads it from there and refetches later.
 */
export const getConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetConfigData, ThrowOnError>
): RequestResult<GetConfigResponses, GetConfigErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({
    responseValidator: async data => await zGetConfigResponse.parseAsync(data),
    url: '/api/v1/config',
    ...options,
  });

/**
 * Stream the daemon's state
 *
 * Server-sent events, each carrying a whole object. `health`: a `Health`, sent on connect and then every few seconds. A `: ping` comment keeps idle connections open. Every event is complete, so a client that reconnects needs no resume cursor.
 */
export const streamEvents = <ThrowOnError extends boolean = false>(
  options?: Options<StreamEventsData, ThrowOnError, StreamEventsResponse>
): Promise<ServerSentEventsResult<StreamEventsResponses>> =>
  (options?.client ?? client).sse.get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({
    responseValidator: async data => await zStreamEventsResponse.parseAsync(data),
    url: '/api/v1/stream',
    ...options,
  });
