// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Public, unauthenticated configuration. Never put a secret here.
 */
export type Config = {
  /**
   * The daemon's display name.
   */
  name: string;
  /**
   * The build's version.
   */
  version: string;
};

export type Health = {
  status: 'ok';
  /**
   * The build's version.
   */
  version: string;
  /**
   * The daemon's clock when it answered.
   */
  at: string;
};

/**
 * RFC 9457 problem details.
 */
export type Problem = {
  type?: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type GetHealthErrors = {
  /**
   * An error, as an RFC 9457 problem.
   */
  default: Problem;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * The daemon is serving.
   */
  200: Health;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/config';
};

export type GetConfigErrors = {
  /**
   * An error, as an RFC 9457 problem.
   */
  default: Problem;
};

export type GetConfigError = GetConfigErrors[keyof GetConfigErrors];

export type GetConfigResponses = {
  /**
   * The public configuration.
   */
  200: Config;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type StreamEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/stream';
};

export type StreamEventsErrors = {
  /**
   * An error, as an RFC 9457 problem.
   */
  default: Problem;
};

export type StreamEventsError = StreamEventsErrors[keyof StreamEventsErrors];

export type StreamEventsResponses = {
  /**
   * Server-sent `health` events.
   */
  200: Health;
};

export type StreamEventsResponse = StreamEventsResponses[keyof StreamEventsResponses];
