// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * Public, unauthenticated configuration. Never put a secret here.
 */
export const zConfig = z.object({
  name: z.string(),
  version: z.string(),
});

export const zHealth = z.object({
  status: z.enum(['ok']),
  version: z.string(),
  at: z.iso.datetime(),
});

/**
 * RFC 9457 problem details.
 */
export const zProblem = z.object({
  type: z._default(z.optional(z.url()), 'about:blank'),
  title: z.string(),
  status: z.int().check(z.gte(100), z.lte(599)),
  detail: z.optional(z.string()),
  instance: z.optional(z.url()),
});

/**
 * The daemon is serving.
 */
export const zGetHealthResponse = zHealth;

/**
 * The public configuration.
 */
export const zGetConfigResponse = zConfig;

/**
 * Server-sent `health` events.
 */
export const zStreamEventsResponse = zHealth;
