// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	GetConfigOperation OperationName = "GetConfig"
	GetHealthOperation OperationName = "GetHealth"
)
